### ISSUE TITLE
Prompt icon not visible in tag manager fields

### ISSUE THREAD

**Issue by arifje** [soerenmeier/craft-gpt-content-generator#5]
Not a real bug, but more of a feature I guess: I enabled the description field we use for entries, but this won't activate the plugin on the [tag manager](https://github.com/ethercreative/tags):
 
![Screenshot 2024-06-12 at 13 14 28](https://github.com/soerenmeier/craft-gpt-content-generator/assets/1286410/76b1ed52-0119-4c92-b299-73e813358b63)

![Screenshot 2024-06-12 at 13 16 52](https://github.com/soerenmeier/craft-gpt-content-generator/assets/1286410/71bae63c-b652-4a66-8be7-420bd914c00e)

Can this be fixed in this plugin or does it need changes on the [tag manager](https://github.com/ethercreative/tags) plugin?

**Comment by soerenmeier** [comment]
Hi, thanks for using my plugin. I will look into it this evening, but I think it should be possible.

**Comment by soerenmeier** [comment]
This should be fixed in v1.2, let me know if something doesn't work as expected

**Comment by arifje** [comment]
Works, thanks!
